### ISSUE TITLE
Support jwilder/nginx-proxy integration

### ISSUE THREAD

**Issue by andylokandy** [xama5/docker-seafile-pro#13]
I ran into an problem when running this image with [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy). 

That is a popular nginx image, which will automatically generate the proxy configuration for each container and provide ssl out-of-box. 
But it has the shortcoming that it can only specify one port for a container, while `docker-seafile-pro` exposes two. 

A solution that I comes up with is to split this image into two, seafile and seahub.

**Comment by andylokandy** [comment]
Relevant: https://github.com/jwilder/nginx-proxy/issues/1042

**Comment by andylokandy** [comment]
I temporally solved this problem by re-exposing 8082 port by another container.

I used the following docker-compose script.

```
  seahub:
    image: xama/docker-seafile-pro
    container_name: seahub
    restart: always
    depends_on:
      - nginx
    expose:
      - "8000"
      - "8082"
    volumes:
      - /var/lib/seafile:/seafile
    environment:
      - VIRTUAL_HOST=~^storage\..*
      - VIRTUAL_PORT=8000
      - CERT_NAME=club

  seafile:
    image: bortels/socat
    container_name: seafile
    restart: always
    depends_on:
      - seahub
    expose:
      - "8082"
    links:
      - seahub
    command: "-dddd TCP-LISTEN:8082,reuseaddr,fork TCP:seahub:8082"
    environment:
      - VIRTUAL_HOST=~^transfer\.storage\..*
      - VIRTUAL_PORT=8082
      - CERT_NAME=club
```
